# SERVER BLOCK 1 configuration
server:
	# Port number the server listens on
	ports: 9010
	# Server names (space-separated) for virtual hosting
	server_names: 48k483x .fr frost.fr
	# Host address for binding the server
	host: 127.0.0.1
	# Maximum allowed size for client request bodies (in bytes)
	client_max_body_size: 2800000
	# Mapping of HTTP error codes to custom error page files
	error_pages:
		301: errorPages/301.html   
		302: errorPages/302.html   
		400: errorPages/400.html 
		403: errorPages/403.html 
		404: errorPages/404.html   
		405: errorPages/405.html  
		408: errorPages/408.html  
		409: errorPages/409.html   
		411: errorPages/411.html   
		413: errorPages/413.html   
		414: errorPages/414.html   
		500: errorPages/500.html   
		501: errorPages/501.html  

	# Location block for the root path "/"
	location: /
		# Document root for this location
		root: ./assets
		# Enable automatic directory listing
		autoindex: on
		# Default file to serve when accessing a directory
		index: index.html
		# Comma-separated list of allowed HTTP methods for this location
		allowed_methods: GET,POST
		# Mapping of file extensions to CGI executables for dynamic content
		cgi_path:
			php: /usr/bin/php-cgi
			py: /usr/bin/python3
			rb: /usr/bin/ruby

	# Location block for the "/ups" path
	location: /ups
		# Document root for this location
		root: ./assets
		# Disable autoindex to prevent directory listing
		autoindex: off
		# Default file to serve for this location
		index: index.php
		# Allowed HTTP methods for this location (includes DELETE)
		allowed_methods: GET,POST,DELETE
		# CGI executables mapping for supported scripts
		cgi_path:
			php: /usr/bin/php-cgi
			py: /usr/bin/python3
			rb: /usr/bin/ruby

# SERVER BLOCK 2 configuration
server:
	# Port number the server listens on
	ports: 7600
	# Server names for virtual hosting (space-separated)
	server_names: 48k483x .fr frost.fr
	# Host address to bind the server instance
	host: 127.0.0.1
	# Maximum allowed size for client request bodies in bytes
	client_max_body_size: 2800000
	# Error pages mapping for various HTTP errors
	error_pages:
		301: errorPages/301.html
		302: errorPages/302.html
		400: errorPages/400.html
		403: errorPages/403.html
		404: errorPages/404.html
		405: errorPages/405.html
		408: errorPages/408.html
		409: errorPages/409.html
		411: errorPages/411.html
		413: errorPages/413.html
		414: errorPages/414.html
		500: errorPages/500.html
		501: errorPages/501.html

	# Location block for the root path "/"
	location: /
		# Document root for this location
		root: ./assets
		# Enable automatic directory listing
		autoindex: on
		# Default file to serve when a directory is accessed
		index: index.html
		# Allowed HTTP methods for this location
		allowed_methods: GET,POST
		# CGI configuration: mapping file extensions to their respective executables
		cgi_path:
			php: /usr/bin/php-cgi
			py: /usr/bin/python3
			rb: /usr/bin/ruby

	# Location block for the "/ups" path
	location: /ups
		# Document root for "/ups"
		root: ./assets
		# Enable autoindex for this location
		autoindex: on
		# Default file for "/ups" location
		index: index.php
		# Allowed HTTP methods (including DELETE)
		allowed_methods: GET,POST,DELETE
		# CGI executables mapping for dynamic script handling
		cgi_path:
			php: /usr/bin/php-cgi
			py: /usr/bin/python3
			rb: /usr/bin/ruby