server:
	ports: 8080
	server_names: example.com www.example.com
	host: 127.0.0.1
	client_max_body_size: 1048576
	error_pages:
		301: errorPages/301.html
		302: errorPages/302.html
		400: errorPages/400.html
		403: errorPages/403.html
		404: errorPages/custom404.html
		500: errorPages/500.html
	location: /
		root: ./assets
		autoindex: on
		index: index.html
		allowed_methods: GET,POST
		cgi_path:
			php: /usr/bin/php-cgi
			py: /usr/bin/python3

server:
	ports: 9090
	server_names: api.example.com
	host: 127.0.0.5
	client_max_body_size: 2097152
	error_pages:
		301: errorPages/301.html
		302: errorPages/302.html
		400: errorPages/400.html
		403: errorPages/403.html
		404: errorPages/custom404.html
		500: errorPages/500.html
	location: /ups
		root: ./assets
		autoindex: off
		index: index.php
		allowed_methods: GET,POST,DELETE
		cgi_path:
			php: /usr/bin/php-cgi
